# Generated by Django 5.0.4 on 2024-05-31 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0059_rename_scope_asmonitor_apitoken_scope_attack_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='#([a-fA-F\\d]{6}|[a-fA-F\\d]{3})')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('tool', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('affected_component', models.CharField(max_length=1024)),
                ('result', models.TextField()),
                ('full_output', models.TextField(blank=True, null=True)),
                ('false_positive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('severity', models.PositiveSmallIntegerField(choices=[(0, 'Informational'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (2, 'Closed')], default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_surface.program')),
            ],
            options={
                'ordering': ['-date_created', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('data', models.CharField(db_index=True, max_length=512)),
                ('scope', models.PositiveSmallIntegerField(choices=[(0, 'In Scope'), (1, 'Undefined'), (2, 'Out of Scope')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.PositiveSmallIntegerField(choices=[(0, 'IP'), (1, 'Network'), (2, 'Domain'), (3, 'Subdomain')])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_surface.program')),
                ('tags', models.ManyToManyField(blank=True, to='attack_surface.tag')),
                ('technologies', models.ManyToManyField(blank=True, to='backend.technology')),
            ],
            options={
                'ordering': ['-last_seen', 'data'],
                'unique_together': {('data', 'program')},
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('port', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('service', models.CharField(blank=True, max_length=32, null=True)),
                ('protocol', models.PositiveSmallIntegerField(choices=[(0, 'TCP'), (1, 'UDP')], default=0)),
                ('banner', models.CharField(blank=True, max_length=1024, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_surface.target')),
            ],
            options={
                'ordering': ['port', 'protocol'],
                'unique_together': {('target', 'port', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_base', models.BooleanField(editable=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_surface.program')),
                ('tags', models.ManyToManyField(blank=True, to='attack_surface.tag')),
                ('technologies', models.ManyToManyField(blank=True, to='backend.technology')),
            ],
            options={
                'ordering': ['-date_updated', 'url'],
                'unique_together': {('program', 'url')},
            },
        ),
    ]
