# Generated by Django 5.2 on 2025-06-29 13:35

import django.db.models.deletion
import pecoret.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advisories", "0001_initial"),
        ("backend", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="cwes",
            field=models.ManyToManyField(to="backend.cwe"),
        ),
        migrations.AddField(
            model_name="advisory",
            name="technology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="backend.technology"
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="advisorycomment",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="advisories.advisory"
            ),
        ),
        migrations.AddField(
            model_name="advisorycomment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advisorycomment",
            name="user_edit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST,
                related_name="advisory_comment_edited_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advisorytimeline",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="advisories.advisory"
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="labels",
            field=models.ManyToManyField(blank=True, to="advisories.label"),
        ),
        migrations.AddField(
            model_name="sharetoken",
            name="advisory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="advisories.advisory"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sharetoken",
            unique_together={("name", "advisory")},
        ),
    ]
