# Generated by Django 4.2.6 on 2023-11-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0002_imageattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageattachment',
            name='caption',
        ),
    ]
