# Generated by Django 5.2 on 2025-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="AdvisoryComment",
        ),
    ]
