# Generated by Django 5.0.6 on 2024-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0005_advisory_alter_imageattachment_advisory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisory',
            old_name='internal_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='advisory',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
