# Generated by Django 5.0.6 on 2024-07-14 09:59

import pecoret.reporting.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0006_rename_internal_name_advisory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='report_template',
            field=models.CharField(choices=pecoret.reporting.utils.get_report_template_choices, max_length=128),
        ),
    ]
