# Generated by Django 5.0.3 on 2024-03-12 18:10

import django.core.validators
import django.db.models.deletion
import pecoret.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0047_technology_apitoken_scope_asmonitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='#([a-fA-F\\d]{6}|[a-fA-F\\d]{3})')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.program')),
                ('tags', models.ManyToManyField(blank=True, to='asmonitor.tag')),
                ('technologies', models.ManyToManyField(blank=True, to='backend.technology')),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
                'unique_together': {('name', 'program', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('severity', models.PositiveSmallIntegerField(choices=[(0, 'Informational'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')])),
                ('proof_text', models.TextField(blank=True, default='')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Fixed'), (2, 'Wont Fix')], default=0)),
                ('cwe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asmonitor_finding_set', to='backend.cwe')),
                ('user', models.ForeignKey(on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST, related_name='asmonitor_finding_set', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.program')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.target')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
