# Generated by Django 5.0.3 on 2024-04-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='tags',
            field=models.ManyToManyField(blank=True, to='asmonitor.tag'),
        ),
    ]
