# Generated by Django 5.0.4 on 2024-04-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0002_finding_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.target')),
            ],
            options={
                'ordering': ['key', 'target'],
                'unique_together': {('target', 'key')},
            },
        ),
    ]
