# Generated by Django 5.0.4 on 2024-05-15 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0003_targetmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='scope',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In Scope'), (1, 'Undefined'), (2, 'Out of Scope')], default=1),
        ),
        migrations.AlterField(
            model_name='target',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('port', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('service', models.CharField(blank=True, max_length=32, null=True)),
                ('protocol', models.PositiveSmallIntegerField(choices=[(0, 'TCP'), (1, 'UDP')], default=0)),
                ('banner', models.CharField(blank=True, max_length=1024, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.target')),
            ],
            options={
                'ordering': ['port', 'protocol'],
                'unique_together': {('target', 'port', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=512)),
                ('scope_type', models.PositiveSmallIntegerField(choices=[(0, 'IP'), (1, 'Network'), (2, 'Domain'), (3, 'Wildcard'), (4, 'Subdomain')])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.program')),
            ],
            options={
                'ordering': ['-date_updated'],
                'unique_together': {('program', 'data')},
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.target')),
            ],
            options={
                'ordering': ['url', '-date_updated'],
                'unique_together': {('target', 'url')},
            },
        ),
    ]
