# Generated by Django 5.0.4 on 2024-05-12 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0003_targetmeta'),
        ('backend', '0055_merge_20240424_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('description', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('scope', models.PositiveSmallIntegerField(choices=[(0, 'In Scope'), (1, 'Undefined'), (2, 'Out of Scope')], default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.program')),
                ('tags', models.ManyToManyField(blank=True, to='asmonitor.tag')),
                ('technologies', models.ManyToManyField(blank=True, related_name='asmonitor_hosts', to='backend.technology')),
            ],
            options={
                'ordering': ['-last_seen', 'ip'],
                'unique_together': {('program', 'ip')},
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.host'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='finding',
            name='target',
        ),
        migrations.AlterModelOptions(
            name='targetmeta',
            options={'ordering': ['key', 'host']},
        ),
        migrations.AlterUniqueTogether(
            name='targetmeta',
            unique_together=set(),
        ),

        migrations.AddField(
            model_name='targetmeta',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.host'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='targetmeta',
            unique_together={('host', 'key')},
        ),
        migrations.RemoveField(
            model_name='targetmeta',
            name='target',
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator(regex='^(?=.{1,255}$)[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\\.?$')])),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.host')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'host')},
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('port', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(65535)])),
                ('service', models.CharField(blank=True, max_length=32, null=True)),
                ('protocol', models.PositiveSmallIntegerField(choices=[(0, 'TCP'), (1, 'UDP')], default=0)),
                ('banner', models.CharField(blank=True, max_length=1024, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.host')),
            ],
            options={
                'ordering': ['port', 'protocol'],
                'unique_together': {('host', 'port', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data', models.CharField(max_length=512)),
                ('scope_type', models.PositiveSmallIntegerField(choices=[(0, 'IP'), (1, 'Network'), (2, 'Domain'), (3, 'Wildcard'), (4, 'Subdomain')])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.program')),
            ],
            options={
                'ordering': ['-date_updated'],
                'unique_together': {('program', 'data')},
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmonitor.host')),
            ],
            options={
                'ordering': ['url', '-date_updated'],
                'unique_together': {('host', 'url')},
            },
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
