# Generated by Django 5.0.4 on 2024-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0004_target_scope_alter_target_ip_alter_target_name_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
