# Generated by Django 5.0.4 on 2024-05-22 07:33

from django.db import migrations, models
from urllib.parse import urlparse


def is_base(url):
    parsed = urlparse(url)
    port = 80
    if parsed.port:
        port = parsed.port
    if parsed.scheme == "https":
        port = 443
    base_url = f"{parsed.scheme}://{parsed.netloc}:{port}"
    if f':{port}' not in url:
        url = f"{parsed.scheme}://{parsed.netloc}:{port}"
    if base_url == url:
        return True
    return False


def calc_is_base(apps, schema_editor):
    URL = apps.get_model('asmonitor', 'URL')
    for url in URL.objects.filter(is_base__isnull=True):
        url.is_base = is_base(url.url)
        url.save()


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0005_finding_description_finding_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_base',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.RunPython(calc_is_base),
    ]
