# Generated by Django 5.0.4 on 2024-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmonitor', '0007_finding_internal_information'),
        ('backend', '0055_merge_20240424_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(blank=True, to='asmonitor.tag'),
        ),
        migrations.AddField(
            model_name='url',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='backend.technology'),
        ),
    ]
