# Generated by Django 5.1.5 on 2025-02-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(blank=True, max_length=518, null=True)),
                ('url', models.URLField()),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('matrix', 'Matrix.org'), ('generic', 'Generic')], max_length=128)),
                ('event_new_target', models.BooleanField(default=False, help_text='New Target created in Attack Surface application.')),
                ('event_critical_scan_finding', models.BooleanField(default=False, help_text='New critical Scan Finding in Attack Surface application.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
