# Generated by Django 5.0 on 2023-12-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_assetchecklist_component_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetchecklist',
            name='component_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'backend'), ('model', 'webapplication')), models.Q(('app_label', 'backend'), ('model', 'service')), models.Q(('app_label', 'backend'), ('model', 'host')), models.Q(('app_label', 'backend'), ('model', 'mobileapplication')), models.Q(('app_label', 'backend'), ('model', 'thickclient')), models.Q(('app_label', 'backend'), ('model', 'genericasset')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
