# Generated by Django 5.0.1 on 2024-01-22 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_alter_assetchecklist_component_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='category_id',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[\\w\\d_-]*$')]),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='item_id',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(regex='^[\\w\\d_-]*$')]),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checklist_id',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w\\d_-]*$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(regex='^[\\w\\d_-]*$')]),
        ),
    ]
