# Generated by Django 5.2 on 2025-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("year", "name", "company")},
        ),
    ]
