# Generated by Django 4.2.6 on 2023-10-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_user_new_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='path',
            new_name='package',
        ),
    ]
