# Generated by Django 4.2.6 on 2023-11-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_objectlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnote',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
