# Generated by Django 5.0 on 2023-12-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_finding_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('accessible', models.PositiveSmallIntegerField(choices=[(0, 'Accessible'), (1, 'Not Accessible'), (2, 'Unknown')], default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Production'), (2, 'Testing'), (3, 'Development'), (4, 'Staging')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='genericasset',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='generic_asset_unique_name'),
        ),
    ]
