# Generated by Django 4.2.6 on 2023-11-25 14:41

from django.db import migrations, models


def initialize_settings(apps, schema_editor):
    Settings = apps.get_model('backend', 'Settings')
    Settings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_finding_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='PeCoReT Project', max_length=128)),
                ('company_street', models.CharField(default='Demo Street 5', max_length=255)),
                ('company_city', models.CharField(default='Demo City', max_length=255)),
                ('company_homepage', models.URLField(default='https://pecoret.github.io')),
                ('company_email', models.EmailField(default='no-reply@pecoret.local', max_length=254)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RunPython(initialize_settings)
    ]
