# Generated by Django 5.0 on 2023-12-11 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_cvss31(apps, schema_editor):
    Finding = apps.get_model('backend', 'Finding')
    for finding in Finding.objects.all():
        score = finding.cvssbasescore
        vector = f"CVSS:3.1/AV:{score.get_av_display()}/AC:{score.get_ac_display()}/PR:{score.get_pr_display()}/UI:{score.get_ui_display()}" \
                 f"/S:{score.get_s_display()}/A:{score.get_a_display()}/C:{score.get_c_display()}/I:{score.get_i_display()}"

        if "None" not in vector:
            finding.cvss_score_31 = vector
            finding.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0038_genericasset_genericasset_generic_asset_unique_name'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvss_score_31',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[
                django.core.validators.RegexValidator(
                    regex='CVSS:3\\.1/AV:[N|A|L|P]/AC:[L|H]/PR:[N|L|H]/UI:[N|R]/S:[C|U]/C:[N|L|H]/I:[N|L|H]/A:[N|L|H]')]),
        ),
        migrations.AlterField(
            model_name='finding',
            name='component_content_type',
            field=models.ForeignKey(
                limit_choices_to=models.Q(models.Q(('app_label', 'backend'), ('model', 'webapplication')),
                                          models.Q(('app_label', 'backend'), ('model', 'service')),
                                          models.Q(('app_label', 'backend'), ('model', 'host')),
                                          models.Q(('app_label', 'backend'), ('model', 'mobileapplication')),
                                          models.Q(('app_label', 'backend'), ('model', 'thickclient')),
                                          models.Q(('app_label', 'backend'), ('model', 'genericasset')),
                                          _connector='OR'), on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'),
        ),
        migrations.RunPython(migrate_cvss31),
        migrations.DeleteModel(
            name='CVSSBaseScore',
        ),
    ]
