# Generated by Django 5.0 on 2024-01-09 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_remove_finding_authenticated_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='path',
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\_]*$')]),
        ),
    ]
