# Generated by Django 5.0 on 2024-01-21 07:38

import pecoret.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_advisory_is_draft_advisory_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='user_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST, related_name='companyinformation_user_edit_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not Disclosed'), (2, 'Disclosed')], default=1),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Members'), (2, 'Team')], default=1),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='user',
            field=models.ForeignKey(on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST, to=settings.AUTH_USER_MODEL),
        ),
    ]
