# Generated by Django 5.0.1 on 2024-02-04 06:41

from django.conf import settings
from django.db import migrations, models

import pecoret.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0045_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingcomment',
            name='user_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST,
                                    related_name='finding_comment_edited_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='findingcomment',
            name='user',
            field=models.ForeignKey(on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisorycomment',
            name='user_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=pecoret.core.models.CASCADE_USER_TO_GHOST,
                                    related_name='advisory_comment_edited_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
