# Generated by Django 5.0.3 on 2024-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_findingcomment_user_edit_alter_findingcomment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cpe', models.CharField(blank=True, max_length=256, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', '-date_updated'],
            },
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope_asmonitor',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Access'), (1, 'Read'), (2, 'Read Write')], default=0),
        ),
    ]
