# Generated by Django 5.0.3 on 2024-03-27 07:13

import django.db.models.deletion
from django.db import migrations, models


def migrate_vendor_to_tech(apps, schema_editor):
    Advisory = apps.get_model("backend", "Advisory")
    Technology = apps.get_model("backend", "Technology")
    for advisory in Advisory.objects.all():
        technology, _created = Technology.objects.get_or_create(name=advisory.product,
                                                                defaults={
                                                                    'homepage': advisory.vendor_url,
                                                                    'vendor': advisory.vendor_name,
                                                                })
        advisory.technology = technology
        advisory.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0048_advisory_researchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='source_code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='vendor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RunPython(migrate_vendor_to_tech),
        migrations.RemoveField(model_name='advisory', name='vendor_url'),
        migrations.RemoveField(model_name='advisory', name='vendor_name'),
        migrations.RemoveField(model_name='advisory', name='product')
    ]
