# Generated by Django 5.0.3 on 2024-03-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_advisory_technology_technology_source_code_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.technology'),
        ),
    ]
