# Generated by Django 5.0.3 on 2024-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_remove_advisorymembership_advisory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='scope_knowledgebase',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Access'), (1, 'Read'), (2, 'Read Write')], default=0),
        ),
    ]
