# Generated by Django 5.0.3 on 2024-04-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_apitoken_scope_knowledgebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Members Only'), (1, 'Pentesters')], default=0),
        ),
    ]
