# Generated by Django 5.0.4 on 2024-04-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_genericasset_technologies_host_technologies_and_more'),
        ('backend', '0054_project_visibility'),
    ]

    operations = [
    ]
