# Generated by Django 5.0.4 on 2024-05-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_merge_20240424_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='child_techs',
            field=models.ManyToManyField(blank=True, to='backend.technology'),
        ),
    ]
