# Generated by Django 5.0.4 on 2024-05-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_technology_child_techs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='child_techs',
            new_name='implicit_technologies',
        ),
    ]
