# Generated by Django 5.0.4 on 2024-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_rename_child_techs_technology_implicit_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='cpe',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
