# Generated by Django 5.0.6 on 2024-07-13 15:03

import django.db.models.deletion
import pecoret.reporting.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_rename_scope_asmonitor_apitoken_scope_attack_surface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='variant',
        ),
        migrations.AlterField(
            model_name='company',
            name='report_template',
            field=models.CharField(choices=pecoret.reporting.utils.get_report_template_choices, max_length=256),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.CharField(choices=pecoret.reporting.utils.get_report_template_choices, max_length=128),
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
