# Generated by Django 5.0.7 on 2024-07-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_remove_report_variant_alter_company_report_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
