# Generated by Django 5.0.7 on 2024-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_auto_20240802_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='vendor',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
