# Generated by Django 5.1.3 on 2024-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_assettype'),
        ('checklists', '0008_assetchecklist_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='technologies',
        ),
        migrations.AlterUniqueTogether(
            name='mobileapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mobileapplication',
            name='project',
        ),
        migrations.RemoveField(
            model_name='mobileapplication',
            name='technologies',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='thickclient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thickclient',
            name='project',
        ),
        migrations.RemoveField(
            model_name='thickclient',
            name='technologies',
        ),
        migrations.AlterUniqueTogether(
            name='webapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='webapplication',
            name='project',
        ),
        migrations.RemoveField(
            model_name='webapplication',
            name='technologies',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-date_updated', 'name']},
        ),
        migrations.AlterModelOptions(
            name='customfieldasset',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='customfieldassetvalue',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='customfieldasset',
            name='ordering',
            field=models.PositiveIntegerField(default=5, help_text='the ordering of the field'),
        ),
        migrations.DeleteModel(
            name='GenericAsset',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='MobileApplication',
        ),
        migrations.DeleteModel(
            name='ThickClient',
        ),
        migrations.DeleteModel(
            name='WebApplication',
        ),
    ]
