# Generated by Django 5.1 on 2024-10-09 14:26

import core.storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=256, upload_to=core.storage.models.upload_path)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
