name: Publish Docker image on release

on:
  workflow_dispatch:
  release:
    types:
      - published


env:
  IMAGE_NAME_SERVER: pecoret-server
  IMAGE_REPO: pecoret
  REGISTRY: ghcr.io

jobs:
  push_to_registry:
    permissions:
      contents: write
      packages: write
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: build and upload images
        run: |
          docker login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker build -t ${{ env.IMAGE_NAME_SERVER }} .
          docker tag ${{ env.IMAGE_NAME_SERVER}} ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME_SERVER }}:$(git describe --abbrev=0 --tags)
          docker tag ${{ env.IMAGE_NAME_SERVER}} ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME_SERVER }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME_SERVER }}:$(git describe --abbrev=0 --tags)
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME_SERVER }}:latest
